# Generated by Django 3.1.7 on 2021-03-10 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Текст')),
                ('description', models.TextField(max_length=200, verbose_name='Поле')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='webapp.status')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='webapp.type')),
            ],
            options={
                'verbose_name': 'Список',
                'verbose_name_plural': 'Списки',
                'db_table': 'lists',
            },
        ),
    ]
